### ISSUE TITLE
Menu Expand/Collapse Button Not Working

### ISSUE THREAD

**Issue by Matts-Hub** [makerfleet/bug_reporting#1]
## Description

Side menu is not collapsable with the button at the top next to the makerfleet logo. When the collapse button is pressed, the rest of the page expands across as though it has collapsed, but it hasn't.

### Browser 
Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)

### Operating System 
Mac OS Version 10.14.1

## Expected Behavior
Menu should collapse to just icons for menu options, with no text next to them

## Current Behavior
Menu does not change at all, but the rest of the page behind it expands as though it has.

## Steps to Reproduce

1. Go to any page on the website
2. Press the menu collapse button next to the logo at the top

**Comment by HakuG** [comment]
Huh weird... It's working for me and I have the same Chrome Version and I'm on Mac OS. If you move your cursor away from the sidebar, it should collapse, only to reopen if you move it back over.

**Comment by Matts-Hub** [comment]
Oh right! That makes sense. I just tried it and got the same behaviour :) May I suggest that it collapses as soon as you press the button, and then moving the mouse over it expands it?

**Comment by HakuG** [comment]
I like it. I think a few people have had this UI problem. I'll put it up as a github issue right away!

**Comment by Matts-Hub** [comment]
Great!
