### ISSUE TITLE
Add quick re-print button to successfully completed public jobs

### ISSUE THREAD

**Issue by vinay30** [makerfleet/bug_reporting#2]
## Context (Environment)

- If we want to print a copy of an object that has already been printed, we have to go through all steps again.
- Would be faster if a quick print button was present which would print the object with the most recent settings that produced a successful print job

![](https://screenshot.click/21-01-tgtir-t94ke.jpg)

### Browser 
n/a

### Operating System 
n/a

**Comment by HakuG** [comment]
@vinay30 Completed and pushed to master.
