### ISSUE TITLE
Changing the filament color in the print setup area should change the color of the 3D model

### ISSUE THREAD

**Issue by vinay30** [makerfleet/bug_reporting#3]
## Context (Environment)

Going through the normal setup and configuration process, I think when the filament color is adjusted (say, from white to red to black, etc), the app should re-draw the 3D model in that new color so that the user can more easily judge whether that's the right color for them.

## Screenshot

![](https://screenshot.click/26-47-cqo86-z08fa.jpg)

**Comment by HakuG** [comment]
Done. Should be viewable on master soon.
