### ISSUE TITLE
Not a part of any fleets on Chrome

### ISSUE THREAD

**Issue by peterhuson** [makerfleet/bug_reporting#4]
## Context (Environment)
Chrome on Macbook Pro. 

### Browser 
Chrome 73.0 -> Fixed in Chrome 77.0

### Operating System 
Mac OS 10.12.6

## Expected Behavior
I would be shown the fleets I am a member of. 

## Current Behavior
The message "Not a part of any fleets" is shown. 

## Steps to Reproduce
1. Downgrade to Chrome 73.0
2. Log in to your account

## Detailed Description
When logging in on Chrome 73.0 I would receive the message "Not a part of any fleets". 

## Possible Implementation
Test on various versions of modern browsers.

**Comment by peterhuson** [comment]
Resolved by updating to Chrome 77.0, feel free to close this if it is seen as a low priority.

**Comment by HakuG** [comment]
Thanks for figuring this out. 

Turns out it's because of a "Promise.all" statement, which is only supported from Chrome right now. I'm moving all "Promise.all" statements back to normal so it works with older versions. 

Should be fixed tonight.

**Comment by HakuG** [comment]
Finally figured it out. "fromEntries" is not supported on browsers after 73. This is a big enough issue to remove fromEntries for now. It makes it incompatible on Safari as well. Thanks for submitting the bug!
